### ISSUE TITLE
PS2: Missing file error with `python zip_submission.py`

### ISSUE THREAD

**Issue by SuperbGecko** [emory-courses/computer-vision#2]
For PS2, when running the command `python zip_submission.py`, I get the following error:   
```
Line 15: dir_list = yaml.load(open('.zip_dir_list.yml'))['directories']
FileNotFoundError: [Errno 2] No such file or directory: '.zip_dir_list.yml'
```
I don't see any file called `.zip_dir_list.yml` within the project files. In the case that this doesn't work, what files do we need to submit?

**Comment by meera1hahn** [comment]
fixed via the following commit: https://github.com/emory-courses/computer-vision/commit/5468eb0b8f6dba15b78e2df88f46389448e9b2c3

please find the file .zip_dir_list.yml in the repo for hw2

**Comment by meera1hahn** [comment]
fixed via the following commit: https://github.com/emory-courses/computer-vision/commit/5468eb0b8f6dba15b78e2df88f46389448e9b2c3

please find the file .zip_dir_list.yml in the repo for hw2
